### PR TITLE
docs(feedback): remove challenge from the url

### PR DESCRIPTION
**Pull request by dcsiebe**
Instead of having the challenge in the url, put it in the body. This
makes the url simpler. Now the id of the challenge isn't needed when
getting the feedback for example.

### CODE REVIEW

**Comment by kvdb** [comment]
I don't see the reason for this patch. when posting feedback, you're always doing it for a specific challenge, no? I don't see why this shouldn't be in the URL. I mean, body is fine too, but we established a pattern here (where id is in url). I'm sure you've got a reason for moving it in the body?

**Comment by joggienl** [comment]
I gave this comment as well: if we do this (which would be fine) it would break the current consistency I guess. So we should then implement it for the other API functions as well to do it like this.

So, what is the main rationale for this patch? Is it just "stylistic" about the simplicity of the URL or were there other reasons as well?

**Comment by dcsiebe** [comment]
To emphasize (since the rationale is already in the commit message):
>Now the id of the challenge isn't needed when getting the feedback for example.

It makes the api simpler for multiple calls (get/put/patch), which is better I believe. This is thus not a 'stylistic' change but rather a functional.
For now I'd like to see this as a trial, see if this is actually better. If so, we might apply that to the rest of the api so it's consistent throughout.

**Comment by kvdb** [comment]
As discussed offline, challenge id is no longer required data to get to the specific feedback id (due to namespace/parent ndb structure)

**Pull request merged**
