### PR TITLE
add user profile metadata to Progress API

### PR DESCRIPTION
**Pull request by macciocu**
As a first step to resolve https://gitlab.com/dcentralized/itslanguage/its-gae/issues/16, in this PR the user profile metadata is added to the Progress API.

### CODE REVIEW

**Comment by codereview-cc** [comment]
Please take a look at https://gitlab.com/dcentralized/itslanguage/its-gae/issues/16, I think I made mistake.

**Comment by kvdb** [comment]
Please take a look at https://gitlab.com/dcentralized/itslanguage/its-gae/issues/16, I think I made mistake.

**Comment by joggienl** [comment]
Indeed, the progress api has nothing to do with profile actually :-)

**Comment by macciocu** [comment]
Erroneous merge request, this branch will not be merged (I've deleted it).

**Pull request closed without merging**
