### PR TITLE
docs(emailauth): create email credentials

### PR DESCRIPTION
**Pull request by dcsiebe**
Document creating email credentials for a user.

### CODE REVIEW

**Comment by Lehren** [comment]
How does this fit in the current domain model? Will a User own an EmailCredentials object?

**Review by Lehren — COMMENTED** [review]
How does this fit in the current domain model? Will a User own an EmailCredentials object?

**Comment by dcsiebe** [comment]
Yes, a user may have one or multiple email credentials. This allows for quite some flexibility and it makes it possible to create credentials for a user.

**Comment by Lehren** [comment]
Ok does this need discussion with @joggienl  and @Kees?

**Comment by dcsiebe** [comment]
I'd love some feedback if you guys have any other ideas, but if @joggienl or @kvdb agrees it's fine I guess. We might change this later on.

**Comment by joggienl** [comment]
As far as I can see this is how we earlier discussed and as expected. OK for me.

**Review by joggienl — APPROVED** [review]

**Review by Lehren — APPROVED** [review]

**Pull request merged**
